version: "3.8"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@user.com
            PGADMIN_DEFAULT_PASSWORD: adminuser
        ports:
            - "8000:80"
        depends_on:
            - postgres
        volumes:
            - pgadmin_data:/var/lib/pgadmin

volumes:
    postgres_data:
    pgadmin_data:
